"""Add user device

Revision ID: 114fb4d7a97e
Revises: 
Create Date: 2025-02-08 05:24:11.066226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114fb4d7a97e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('device_type', sa.Enum('TABLET', 'MOBILE', 'DESKTOP', name='devicetype'), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('browser_type', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'user_id', name='uq_device_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_devices')
    # ### end Alembic commands ###
